name: Build Pango

on: [push]

jobs:
  build_bin:
    name: Build Pango Windows for Manim
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - msystem: MINGW64
            arch: x86_64
          - msystem: MINGW32
            arch: i686
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        name: Setup Msys
        with:
          msystem: ${{ matrix.msystem }}
          install: mingw-w64-${{ matrix.arch }}-pango
          update: true
      - shell: msys2 {0}
        env:
          MSYSTEM: ${{ matrix.msystem }}
        run: |
          mkdir "pango"
          dir "/${MSYSTEM}/bin"
          mv "/${MSYSTEM}/bin" "pango"
          dir "/${MSYSTEM}"

      - uses: actions/upload-artifact@v2
        with:
         name: pango.${{ matrix.msystem }}
         path: pango
